name: Expo CI CD
on:
  push:
    branches: [ master ]
jobs:
  build-for-android:
    runs-on: macos-latest
    timeout-minutes: 3600
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - name: Install deps
        run: yarn install
      - name: Image optimization
        run: npx expo-optimize
      - name: Build Android APK Bundle
        run: expo build:android
  build-for-IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      #      - uses: actions/setup-java@v1.4.3
      #        with:
      #          java-version: '9.0.4' # The JDK version to make available on the path.
      #          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
      #          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: sinoru/actions-setup-xcode@v1.1.2
        with:
          xcode-version: '11.2.1' # Exact version of a Xcode version to use
          apple-id: ${{ secrets.EXPO_APPLE_ID }} # Apple ID to download from Apple Developer when Xcode not available in local
          apple-id-password: ${{ secrets.EXPO_APPLE_PASSWORD }}
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install deps
        run: yarn install
      - name: Optimize image
        run: npx expo-optimize
      - name: Export Password P12
        run: export EXPO_IOS_P12_PASSWORD='enlace5430,vituperating'
      - name: Build iOS app
        run: >
          expo build:ios
          -t archive
          --team-id 5UWGGHF8U7
          --dist-p12-path ./apple/CertificatesP12.p12
          --push-id RDRBQZ38N4
          --push-p8-path ./apple/CertificatesP8.p8
          --provisioning-profile-path ./apple/diadiemthainguyen.mobileprovision
          --release-channel production
        env:
          EXPO_APP_SPECIFIC_PASSWORD: ${{secrets.EXPO_APP_SPECIFIC_PASSWORD}}
          EXPO_IOS_DIST_P12_PASSWORD: ${{EXPO_IOS_P12_PASSWORD}}
